version: "3"

services:
  builder:
    build:
      context: builder
    image: eosamsterdam/builder

  nodeosd:
    build:
      context: .
    image: eosamsterdam/eos
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir

  keosd:
    image: eosamsterdam/eos
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
